// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pycjecmlvfkwkcsctrpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5Y2plY21sdmZrd2tjc2N0cnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODg5NDMsImV4cCI6MjA2Mzc2NDk0M30.hwx0B7Zk2p9cS03HDSXsutavZXD1Bjcwo-pIYmWVbew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);